### ISSUE TITLE
Error when running ember s

### ISSUE THREAD

**Issue by bascan** [simplabs/ember-cli-simple-auth-example#13]
I installed the project with:

```
git clone https://github.com/simplabs/ember-simple-auth-example.git
cd ember-simple-auth-example/
npm install
bower install
```
Now when I run ember s the following error occurs:
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\Users\basca\IdeaProjects\ember-simple-auth-example\node_modules\ember-cli\node_modules\configstore\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

```
$ npm --version
5.6.0

$ bower --version
1.8.2
```

**Comment by marcoow** [comment]
This isn't really well-maintained (I'll archive it now) - I'd suggest to run the [dummy app](https://github.com/simplabs/ember-simple-auth#example-app) from the main ESA repo.
